
export const PRODUCTS = [
    {
        id: 1,
        name: "Calming Chamomile Tea",
        slug: "calming-chamomile-tea",
        description: "Experience the soothing embrace of our premium organic chamomile. Sourced from the pristine valleys of the Himalayas, these flowers are hand-picked at dawn to preserve their essential oils. Perfect for winding down after a stressful day, this tea promotes deep, restorative sleep and aids digestion.",
        shortDescription: "Relax after a long day with our premium organic chamomile flowers.",
        price: 299,
        category: "Tea",
        image: "/images/products/chamomile-tea.png",
        rating: 5,
        reviews: 128,
        stock: 50,
        ingredients: ["Organic Chamomile Flowers (Matricaria recutita)"],
        benefits: ["Promotes Sleep", "Reduces Anxiety", "Digestive Aid"],
    },
    {
        id: 2,
        name: "Golden Turmeric Elixir",
        slug: "golden-turmeric-elixir",
        description: "A potent anti-inflammatory blend of turmeric, ginger, and black pepper for joint health. This ancient recipe has been perfected to maximize absorption and deliver immediate relief from inflammation.",
        shortDescription: "A potent anti-inflammatory blend of turmeric, ginger, and black pepper.",
        price: 549,
        category: "Supplements",
        image: "/images/products/turmeric-elixir.png",
        rating: 4,
        reviews: 85,
        stock: 0,
        ingredients: ["Organic Turmeric", "Ginger Root", "Black Pepper Extract"],
        benefits: ["Anti-inflammatory", "Joint Support", "Immunity Boost"],
    },
    {
        id: 3,
        name: "Organic Matcha Powder",
        slug: "organic-matcha-powder",
        description: "Ceremonial grade matcha sourced directly from Japan. High in antioxidants and energy. Whisk up a bowl of focus and clarity with our vibrant green matcha powder.",
        shortDescription: "Ceremonial grade matcha sourced directly from Japan.",
        price: 799,
        category: "Tea",
        image: "/images/products/matcha-powder.png",
        rating: 5,
        reviews: 210,
        stock: 20,
        ingredients: ["100% Organic Matcha Green Tea"],
        benefits: ["High Energy", "Focus & Clarity", "Metabolism Boost"],
    },
    {
        id: 4,
        name: "Lavender Essential Oil",
        slug: "lavender-essential-oil",
        description: "Pure distilled lavender oil for aromatherapy and skin care. 100% organic and therapeutic grade. Add a few drops to your diffuser or pillow for a peaceful night's sleep.",
        shortDescription: "Pure distilled lavender oil for aromatherapy and skin care.",
        price: 399,
        category: "Oils",
        image: "/images/products/lavender-oil.png",
        rating: 5,
        reviews: 94,
        stock: 100,
        ingredients: ["Lavandula Angustifolia Oil"],
        benefits: ["Relaxation", "Sleep Aid", "Skin Soothing"],
    },
    {
        id: 5,
        name: "Ashwagandha Root Powder",
        slug: "ashwagandha-root-powder",
        description: "Ancient ayurvedic adaptogen for stress relief and energy. Balance your hormones and build resilience to stress with this powerful root powder.",
        shortDescription: "Ancient ayurvedic adaptogen for stress relief and energy.",
        price: 449,
        category: "Supplements",
        image: "/images/products/ashwagandha-powder.png",
        rating: 4,
        reviews: 56,
        stock: 30,
        ingredients: ["Organic Ashwagandha Root"],
        benefits: ["Stress Relief", "Hormonal Balance", "Strength"],
    },
    {
        id: 6,
        name: "Peppermint Oil",
        slug: "peppermint-oil",
        description: "Refreshing essential oil for focus and digestive health. Inhale the crisp aroma to clear your mind or dilute and massage onto adrenals for an energy boost.",
        shortDescription: "Refreshing essential oil for focus and digestive health.",
        price: 349,
        category: "Oils",
        image: "/images/products/peppermint-oil.png",
        rating: 5,
        reviews: 112,
        stock: 80,
        ingredients: ["Peppermint Essential Oil"],
        benefits: ["Focus", "Headache Relief", "Digestive Health"],
    },
    {
        id: 7,
        name: "Echinacea Immune Boost",
        slug: "echinacea-immune-boost",
        description: "Natural immune system support from organic echinacea. Stay healthy year-round with our potent echinacea supplement, designed to activate your body's natural defenses.",
        shortDescription: "Natural immune system support from organic echinacea.",
        price: 599,
        category: "Supplements",
        image: "/images/products/echinacea-supplement.png",
        rating: 5,
        reviews: 42,
        stock: 45,
        ingredients: ["Organic Echinacea Purpurea", "Vitamin C", "Zinc"],
        benefits: ["Immune Support", "Faster Recovery", "Respiratory Health"],
    },
    {
        id: 8,
        name: "Green Tea Blend",
        slug: "green-tea-blend",
        description: "Antioxidant-rich green tea with hints of jasmine. A delicate and refreshing blend that cleanses the palate and invigorates the senses.",
        shortDescription: "Antioxidant-rich green tea with hints of jasmine.",
        price: 399,
        category: "Tea",
        image: "/images/products/green-tea-blend.png",
        rating: 4,
        reviews: 67,
        stock: 60,
        ingredients: ["Organic Green Tea", "Jasmine Blossoms"],
        benefits: ["Antioxidant Rich", "Weight Management", "Heart Health"],
    }
];

export const getProduct = (slug) => {
    return PRODUCTS.find((p) => p.slug === slug);
};

export const getFeaturedProducts = () => {
    return PRODUCTS.slice(0, 4); // Just return the first 4 for now
};

export const getProductCategories = () => {
    return ["All", ...new Set(PRODUCTS.map((p) => p.category))];
};
